# This is a basic workflow to help you get started with Actions

name: PushDir2AnotherReop

on:
  push:
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_ACTIONS_P2AR }}
        with:
          source-directory: 'build'
          destination-github-username: 'TearsDrifted'
          destination-repository-name: 'tearsdrifted.github.io'
          user-email: straydrop411@gmail.com
          target-branch: 'develop'
